export const cssVars = {
    // widget cssVars
    switch_color: 'switch.color',
    'switch_font-size': 'switch.fontSize',
    'switch_font-weight': 'switch.fontWeight',
    'switch_font-style': 'switch.fontStyle',
    'switch_margin-left': 'switch.marginLeft',
    'switch_margin-right': 'switch.marginRight',
    switch_align: 'switch.align',
    'switch-prefix_width': 'switch.prefixIcon.width',
    'switch-prefix_height': 'switch.prefixIcon.height',
    'switch-prefix-icon_color': 'switch.prefixIcon.color',
    'switch-prefix-icon_font-size': 'switch.prefixIcon.fontSize',
    'switch-prefix-icon_background': 'switch.prefixIcon.background',
    'switch-prefix-icon_box-shadow': 'switch.prefixIcon.boxShadow',
    'switch-prefix-icon_border-radius': 'switch.prefixIcon.borderRadius',
    'switch-postfix_width': 'switch.postfixIcon.width',
    'switch-postfix_height': 'switch.postfixIcon.height',
    'switch-postfix-icon_color': 'switch.postfixIcon.color',
    'switch-postfix-icon_font-size': 'switch.postfixIcon.fontSize',
    'switch-postfix-icon_background': 'switch.postfixIcon.background',
    'switch-postfix-icon_box-shadow': 'switch.postfixIcon.boxShadow',
    'switch-postfix-icon_border-radius': 'switch.postfixIcon.borderRadius',
    'month-cell_gradient-min-color': 'gradientMinColor',
    'month-cell_gradient-max-color': 'gradientMaxColor',
    'widget_font-family': 'fontFamily',

    // year cssVars
    'month-header_color': 'modeYear.header.color',
    'month-header_font-size': 'modeYear.header.fontSize',
    'month-header_font-weight': 'modeYear.header.fontWeight',
    'month-header_text-align': 'modeYear.header.align',
    'year-block_width': 'modeYear.blocks.width',
    'year-block_height': 'modeYear.blocks.height',
    'year-block_background': 'modeYear.blocks.background',
    'year-block_box-shadow': 'modeYear.blocks.boxShadow',
    'year-block_border-radius': 'modeYear.blocks.borderRadius',
    'year-calendar_vertical-gap': 'modeYear.blocks.verticalGap',
    'year-calendar_horizontal-gap': 'modeYear.blocks.horizontalGap',
    'year-cell_width': 'modeYear.cells.width',
    'year-cell_height': 'modeYear.cells.height',
    'year-cell_border-radius': 'modeYear.cells.borderRadius',
    'year-cells-wrapper_vertical-gap': 'modeYear.cells.verticalGap',
    'year-cells-wrapper_horizontal-gap': 'modeYear.cells.horizontalGap',
    'year-title_color': 'modeYear.title.color',
    'year-title_font-size': 'modeYear.title.fontSize',
    'year-title_font-weight': 'modeYear.title.fontWeight',
    'year-title_text-align': 'modeYear.title.align',

    // month cssVars
    'month-date_color': 'modeMonth.date.color',
    'month-date_font-size': 'modeMonth.date.fontSize',
    'month-date_text-align': 'modeMonth.date.align',
    'month-block_width': 'modeMonth.blocks.width',
    'month-block_height': 'modeMonth.blocks.height',
    'month-block_background': 'modeMonth.blocks.background',
    'month-block_box-shadow': 'modeMonth.blocks.boxShadow',
    'month-block_border-radius': 'modeMonth.blocks.borderRadius',
    'month-block_vertical-gap': 'modeMonth.blocks.verticalGap',
    'month-block_horizontal-gap': 'modeMonth.blocks.horizontalGap',
    'date--active_outline-color': 'modeMonth.border.color',
    'date--active_outline-width': 'modeMonth.border.width'
};

export const dateCssVarsStyle = {
    'date-metric_color': 'color',
    'date-metric_font-size': 'fontSize',
    'date-metric_font-style': 'fontStyle',
    'date-metric_font-weight': 'fontWeight',
    'date-metric_text-align': 'align',
    'date-metric-prefix_color': 'prefix.color',
    'date-metric-prefix_font-size': 'prefix.fontSize',
    'date-metric-postfix_color': 'postfix.color',
    'date-metric-postfix_font-size': 'postfix.fontSize'
};
